### ISSUE TITLE
Error is not output when validate invalid config.yml

### ISSUE THREAD

**Issue by kubosho** [circle-cli/circle-cli#32]
## Environment

- OS: `macOS 10.13.6`
- circle-cli: `0.1.0`

## Reproduce

1. Put `config.yml` to `.circleci/`
2. Run `circleci config validate -c .circleci/config.yml`

## Expected

Thrown an error in CLI.

In https://codebeautify.org/yaml-validator the following error output.

```
Error : Reference "image" does not exist.
Line : image: *image  undefined
```

## Actual

`.circleci/config.yml is valid` output in CLI.

## config.yml

This YAML file is invalid.

```yaml
version: 2

jobs:
  build:
    docker:
      - image: *image
    steps:
      - checkout
      - run: <command>
  test:
    docker:
      - image: *image
    steps:
      - checkout
      - run: <command>

image: &image
    circleci/<language>:<version TAG>

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
```
